kind: pipeline
name: x86_64-linux

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: nixos/nix
  commands:
  - nix-shell -p cachix -I nixpkgs=nixpkgs --run 'cachix use holo; nix-build -A overlay | cachix push holo'
  environment:
    CACHIX_SIGNING_KEY:
      from_secret: cachix_signing_key
