# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "holo-cli-unstable-${version}";
  version = "2019-06-07";
  rev = "7cb93f1e47af6be0b6c6983610affc1cf3bf2c2c";

  goPackagePath = "github.com/Holo-Host/holo-cli";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/Holo-Host/holo-cli";
    sha256 = "00fzipyjwrsvascmy71x5v1cx1ibh4sy7hmaybj0hdwwfn9zq6yd";
  };

  goDeps = ./deps.nix;


  meta = with stdenv.lib; {
    description = "holo-cli";
    homepage    = https://github.com/Holo-Host/holo-cli;
    license     = licenses.free;
    platforms   = platforms.unix;
    maintainers = [ maintainers.samrose ];

  };
}
