# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "holo-cli-unstable-${version}";
  version = "2019-06-07";
  rev = "895d1dcdf15f161e370b87d0e55a48b8662b0833";

  goPackagePath = "github.com/Holo-Host/holo-cli";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/Holo-Host/holo-cli";
    sha256 = "1rs2a4ahpi5g42mj1hiz34vhb6wlpcsrvnpahzn2v6n86c4pa8z1";
  };

  goDeps = ./deps.nix;


  meta = with stdenv.lib; {
    description = "holo-cli";
    homepage    = https://github.com/Holo-Host/holo-cli;
    license     = licenses.free;
    platforms   = platforms.unix;
    maintainers = [ maintainers.samrose ];

  };
}
