# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "holo-cli-unstable-${version}";
  version = "2019-07-12";
  rev = "34c61a95a66b9766967ea54f1ae193ab2dc12818";

  goPackagePath = "github.com/Holo-Host/holo-cli";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/Holo-Host/holo-cli";
    sha256 = "1kkv7lpc4211yyzlvxqg1ha7aigbmhsx756372lz3d92nwr135sb";
  };

  goDeps = ./deps.nix;


  meta = with stdenv.lib; {
    description = "holo-cli";
    homepage    = https://github.com/Holo-Host/holo-cli;
    license     = licenses.free;
    platforms   = platforms.unix;
    maintainers = [ maintainers.samrose ];

  };
}
