# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "holo-cli-unstable-${version}";
  version = "2019-08-22";
  rev = "973212a56941395cd2076a7480173c0a267791d5";

  goPackagePath = "github.com/Holo-Host/holo-cli";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/Holo-Host/holo-cli";
    sha256 = "17ybwchwzb8bgqc46m1w9dxy0mwm7q2bcl60hx5y89wkb9wr3agw";
  };

  goDeps = ./deps.nix;

  meta = with stdenv.lib; {
    license = licenses.asl20;
    platforms = platforms.linux;
  };
}

