# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/BurntSushi/toml";
    fetch = {
      type = "git";
      url = "https://github.com/BurntSushi/toml";
      rev = "3012a1dbe2e4bd1391d42b32f0577cb7bbc7f005";
      sha256 = "1fjdwwfzyzllgiwydknf1pwjvy49qxfsczqx5gz3y0izs7as99j6";
    };
  }
  {
    goPackagePath = "github.com/badoux/checkmail";
    fetch = {
      type = "git";
      url = "https://github.com/badoux/checkmail";
      rev = "9661bd69e9ad6fce1f7579022bdab0440807722a";
      sha256 = "13dq8acrh4dml3lbab5ajv0bymh3s1vnzjdcv71qrhy6wdvv9fnv";
    };
  }
  {
    goPackagePath = "github.com/chzyer/readline";
    fetch = {
      type = "git";
      url = "https://github.com/chzyer/readline";
      rev = "2972be24d48e78746da79ba8e24e8b488c9880de";
      sha256 = "104q8dazj8yf6b089jjr82fy9h1g80zyyzvp3g8b44a7d8ngjj6r";
    };
  }
  {
    goPackagePath = "github.com/fsnotify/fsnotify";
    fetch = {
      type = "git";
      url = "https://github.com/fsnotify/fsnotify";
      rev = "1485a34d5d5723fea214f5710708e19a831720e4";
      sha256 = "0h2g3603z3zsnagxv5dlgzclq1hp2b95wl7c0k4m9ccaif4i8hjf";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/hcl";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/hcl";
      rev = "cf7d376da96d9cecec7c7483cec2735efe54a410";
      sha256 = "0i1zhgpyvvgwkz74k8wd3sygsap1saqv37rw0j5vdpaazmpr1qkb";
    };
  }
  {
    goPackagePath = "github.com/juju/ansiterm";
    fetch = {
      type = "git";
      url = "https://github.com/juju/ansiterm";
      rev = "720a0952cc2ac777afc295d9861263e2a4cf96a1";
      sha256 = "0n6j0y7xhashp8gdkdl0r7vlbkdrkymrzxn9hxrx522k2isggs7h";
    };
  }
  {
    goPackagePath = "github.com/lunixbochs/vtclean";
    fetch = {
      type = "git";
      url = "https://github.com/lunixbochs/vtclean";
      rev = "88cfb0c2efe8ed7b0ccf0af83db39359829027bb";
      sha256 = "0jqn33l1kzy4dk66zbvxz7rlgkgg34s9mhc8z0lrz0i88466zhd8";
    };
  }
  {
    goPackagePath = "github.com/magiconair/properties";
    fetch = {
      type = "git";
      url = "https://github.com/magiconair/properties";
      rev = "de8848e004dd33dc07a2947b3d76f618a7fc7ef1";
      sha256 = "19zqw1x0w0crh8zc84yy82nkcc5yjz72gviaf2xjgfm5a8np7nyb";
    };
  }
  {
    goPackagePath = "github.com/manifoldco/promptui";
    fetch = {
      type = "git";
      url = "https://github.com/manifoldco/promptui";
      rev = "748542ed5f25c8bc3207759215f349c0fe2ae4c4";
      sha256 = "1l0msvja8zh97apnmldq45fi7chc2wpgsmbqw1d80cwg1g3xjd0d";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-colorable";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-colorable";
      rev = "388941e3ea99c461d2bc2747eaf27741b6dda096";
      sha256 = "1kbqr7kfc0as5zwvqi2z8065darzs9g1mpbw4hba996i93iy14mk";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-isatty";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-isatty";
      rev = "bf9a1dea1961e1d831824fb135332bfb8c10e8b8";
      sha256 = "1h00925ym1vf2b1l4jf74hnzzlns1445wg44wlbw7x05062ag7ji";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/go-homedir";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/go-homedir";
      rev = "af06845cf3004701891bf4fdb884bfe4920b3727";
      sha256 = "0ydzkipf28hwj2bfxqmwlww47khyk6d152xax4bnyh60f4lq3nx1";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/mapstructure";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/mapstructure";
      rev = "3536a929edddb9a5b34bd6861dc4a9647cb459fe";
      sha256 = "03bpv28jz9zhn4947saqwi328ydj7f6g6pf1m2d4m5zdh5jlfkrr";
    };
  }
  {
    goPackagePath = "github.com/pelletier/go-toml";
    fetch = {
      type = "git";
      url = "https://github.com/pelletier/go-toml";
      rev = "781fbae71e40e8e598206a0ac02c680d64df2fd0";
      sha256 = "1frqmhyfn34qslvj9jnixrr2dqyy0jirkjd5vd98wwraq8m8cn33";
    };
  }
  {
    goPackagePath = "github.com/spf13/afero";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/afero";
      rev = "588a75ec4f32903aa5e39a2619ba6a4631e28424";
      sha256 = "0j9r65qgd58324m85lkl49vk9dgwd62g7dwvkfcm3k6i9dc555a9";
    };
  }
  {
    goPackagePath = "github.com/spf13/cast";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/cast";
      rev = "c01685bb8421cecb276fa517e91f757215f980b3";
      sha256 = "0vri4sjscz0x4chw45r94d2wwvgd7mi9a9ikc1maqq6qd5jxx42p";
    };
  }
  {
    goPackagePath = "github.com/spf13/cobra";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/cobra";
      rev = "b80588d523ec50c7fee20218426cf2ff70920f06";
      sha256 = "0gl861bn6bb45ands4742xzaxdvl69r4an1v7cyfis7mc450j7lg";
    };
  }
  {
    goPackagePath = "github.com/spf13/jwalterweatherman";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/jwalterweatherman";
      rev = "94f6ae3ed3bceceafa716478c5fbf8d29ca601a1";
      sha256 = "1ywmkwci5zyd88ijym6f30fj5c0k2yayxarkmnazf5ybljv50q7b";
    };
  }
  {
    goPackagePath = "github.com/spf13/pflag";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/pflag";
      rev = "972238283c0625cf3e881de7699ba8f2524c340a";
      sha256 = "194h0lq3s27wcxcgahjl350x46v116x81zgkgh98q9v5iydig28l";
    };
  }
  {
    goPackagePath = "github.com/spf13/viper";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/viper";
      rev = "e697d557b7f549ddf91098cef2ad6e92176dbcdf";
      sha256 = "1jff680236ljw0v91a1z595c1zm8w8agzxymn1h40dbxx24sa0y2";
    };
  }
  {
    goPackagePath = "github.com/subosito/gotenv";
    fetch = {
      type = "git";
      url = "https://github.com/subosito/gotenv";
      rev = "422ef8095f112cfaf9f40c368e0b9ae8c0714cfb";
      sha256 = "0rw31m59z0cf0kim43rlgjv4sx9q3y7j3dnhqnwx9p454yp0wqq9";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "fde4db37ae7ad8191b03d30d27f258b5291ae4e3";
      sha256 = "16k4w4pzziq1kln18k5fg01qgk4hpzb5xsm7175kaky6d6gwyhg3";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "342b2e1fbaa52c93f31447ad2c6abc048c63e475";
      sha256 = "0flv9idw0jm5nm8lx25xqanbkqgfiym6619w575p7nrdh0riqwqh";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "51d6538a90f86fe93ac480b35f37b2be17fef232";
      sha256 = "01wj12jzsdqlnidpyjssmj0r4yavlqy7dwrg7adqd8dicjc4ncsa";
    };
  }
]

